name: Deploy to GCP VM

on:
  push:
    branches:
      - main # Se activa en cada push a la rama principal
  workflow_dispatch: # Permite ejecutarlo manualmente

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="gcp_project_id=${{ secrets.GCP_PROJECT_ID }}"
        working-directory: ./terraform

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Copy project files to VM
        run: |
          gcloud compute scp --recurse . "php-app-vm:~/app" --zone "us-central1-a" --project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Run Docker Compose on VM
        run: |
          gcloud compute ssh "php-app-vm" --zone "us-central1-a" --project "${{ secrets.GCP_PROJECT_ID }}" --command="
            cd ~/app
            sudo docker-compose up --build -d
          "
